import { type GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";
import { getSession, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import Footer from "../../components/Footer";
import Image from "next/image";
import { useState } from "react";
import Link from "next/link";

type Props = {
  session: any;
};

const Dashboard: NextPage<Props> = (props: Props) => {
  const { data: session, status } = useSession();
  const [sideBar, toggleSideBar] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="sticky top-0 max-h-24 bg-white pt-2 lg:py-8">
        <div className="mx-auto w-full px-4 sm:px-6 lg:px-8">
          <nav className="relative flex h-16 items-center justify-between border-2 border-black bg-white lg:h-24 lg:rounded-md lg:px-8 lg:py-6 lg:shadow-brutalist-4">
            <button
              type="button"
              className="ml-5 inline-flex rounded-md p-2 text-black transition-all duration-200 hover:bg-gray-100 focus:bg-gray-100"
              onClick={() => toggleSideBar(!sideBar)}
            >
              {sideBar ? (
                <svg
                  width="96"
                  height="96"
                  viewBox="0 0 96 96"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                  className="h-6 w-6"
                >
                  <rect
                    x="18"
                    y="18"
                    width="68"
                    height="68"
                    fill="black"
                    stroke="black"
                    stroke-width="4"
                    stroke-linejoin="round"
                  />
                  <rect
                    x="10"
                    y="10"
                    width="68"
                    height="68"
                    fill="#FF5E5E"
                    stroke="black"
                    stroke-width="4"
                    stroke-linejoin="round"
                  />
                  <path
                    d="M60.9705 27.0295L27.0293 60.9707"
                    stroke="black"
                    stroke-width="8"
                  />
                  <path
                    d="M27.0295 27.0295L60.9707 60.9707"
                    stroke="black"
                    stroke-width="8"
                  />
                </svg>
              ) : (
                <svg
                  className="h-6 w-6"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M4 6h16M4 12h16m-7 6h7"
                  />
                </svg>
              )}
            </button>

            <div className="flex-shrink-0">
              <Link href="/">
                <Image
                  width={300}
                  height={300}
                  src="./assets/logo.svg"
                  className="h-10 w-auto sm:h-10"
                  alt=""
                />
              </Link>
            </div>

            <div className="mr-4 rounded-full border-4 border-brutal-blue shadow-brutalist-4">
              <Image
                width={32}
                height={32}
                src={session?.user?.image || ""}
                className="rounded-full lg:h-12 lg:w-12"
                alt=""
              />
            </div>
          </nav>
        </div>
      </header>
      <main>
        <div className="mt-12 flex flex-row items-start p-1 lg:p-6">
          {sideBar && (
            <div className="flex-5 sticky top-32 h-full w-[250px] flex-col justify-center overflow-auto p-4">
              <ul>
                <li className="pb-2">
                  <button
                    aria-label="New Project"
                    className="flex w-full items-center rounded border-2 border-black bg-brutal-red py-3 px-5 text-xs font-medium text-white shadow-brutalist-2 ring-offset-2 hover:bg-red-500 focus:outline-none focus:ring-2"
                  >
                    <svg
                      width="17"
                      height="17"
                      viewBox="0 0 17 17"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                      className="mr-2 h-4 w-4"
                    >
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M8.69141 2.42324C5.15678 2.42324 2.29141 5.28862 2.29141 8.82324C2.29141 12.3579 5.15678 15.2232 8.69141 15.2232C12.226 15.2232 15.0914 12.3579 15.0914 8.82324C15.0914 5.28862 12.226 2.42324 8.69141 2.42324ZM0.691406 8.82324C0.691406 4.40496 4.27313 0.823242 8.69141 0.823242C13.1097 0.823242 16.6914 4.40496 16.6914 8.82324C16.6914 13.2415 13.1097 16.8232 8.69141 16.8232C4.27313 16.8232 0.691406 13.2415 0.691406 8.82324Z"
                        fill="currentColor"
                      ></path>
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M8.69141 4.82324C9.13323 4.82324 9.49141 5.18141 9.49141 5.62324V8.02324H11.8914C12.3332 8.02324 12.6914 8.38141 12.6914 8.82324C12.6914 9.26507 12.3332 9.62324 11.8914 9.62324H9.49141V12.0232C9.49141 12.4651 9.13323 12.8232 8.69141 12.8232C8.24958 12.8232 7.89141 12.4651 7.89141 12.0232V9.62324H5.49141C5.04958 9.62324 4.69141 9.26507 4.69141 8.82324C4.69141 8.38141 5.04958 8.02324 5.49141 8.02324H7.89141V5.62324C7.89141 5.18141 8.24958 4.82324 8.69141 4.82324Z"
                        fill="currentColor"
                      ></path>
                    </svg>
                    <span aria-label="Project">Curriculum</span>
                  </button>
                </li>
                <li className="flex flex-row items-center py-4">
                  <svg
                    width="96"
                    height="96"
                    viewBox="0 0 96 96"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                    className="mr-1 h-6 w-6"
                  >
                    <rect
                      x="18"
                      y="18"
                      width="68"
                      height="68"
                      fill="black"
                      stroke="black"
                      stroke-width="4"
                      stroke-linejoin="round"
                    />
                    <rect
                      x="10"
                      y="10"
                      width="68"
                      height="68"
                      fill="#00FF75"
                      stroke="black"
                      stroke-width="4"
                      stroke-linejoin="round"
                    />
                    <rect x="23" y="46" width="19" height="19" fill="black" />
                    <rect x="45" y="46" width="19" height="19" fill="black" />
                    <rect x="23" y="24" width="19" height="19" fill="black" />
                    <rect
                      x="46.5"
                      y="21.5"
                      width="20"
                      height="20"
                      fill="#00FF75"
                      stroke="black"
                      stroke-width="3"
                    />
                  </svg>
                  <span className="ml-2">Curriculums </span>
                </li>
                <li className="flex flex-row items-center py-4">
                  <svg
                    width="96"
                    height="96"
                    viewBox="0 0 96 96"
                    fill="none"
                    className="mr-1 h-6 w-6"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M86 18H18V86H86V18Z"
                      fill="black"
                      stroke="black"
                      stroke-width="4"
                      stroke-linejoin="round"
                    />
                    <path
                      d="M78 10H10V78H78V10Z"
                      fill="#FFD600"
                      stroke="black"
                      stroke-width="4"
                      stroke-linejoin="round"
                    />
                    <path
                      d="M31 64V48H23V64H31Z"
                      fill="black"
                      stroke="black"
                      stroke-width="4"
                    />
                    <path
                      d="M47 64V40H39V64H47Z"
                      fill="black"
                      stroke="black"
                      stroke-width="4"
                    />
                    <path
                      d="M64 64V24H55V64H64Z"
                      fill="black"
                      stroke="black"
                      stroke-width="4"
                    />
                  </svg>

                  <span className="ml-2">Analytics</span>
                </li>
              </ul>
            </div>
          )}

          <div className="flex-5 w-full p-6">
            <section className="h-80 bg-brutal-red">session 1</section>
            <section className="h-80 bg-brutal-blue">section 2</section>
            <section className="h-80 bg-brutal-yellow">section 3</section>
            <section className="h-80 bg-brutal-green">section 4</section>
            <section className="h-80 bg-brutal-red">section 5</section>
          </div>
        </div>
      </main>
    </>
  );
};

export default Dashboard;
