import { type GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";
import { getSession, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import Footer from "../../components/Footer";

const Dashboard: NextPage = () => {
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Footer />
    </>
  );
};

export default Dashboard;
