import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import Footer from "../../components/Footer";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full flex-col items-center justify-center bg-gradient-to-b">
        <div className="bg-white">
          <header className="bg-white bg-opacity-30">
            <div className="mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex h-16 items-center justify-between lg:h-20">
                <div className="flex-shrink-0">
                  <Link href="/">
                    <Image
                      width={300}
                      height={300}
                      src="./assets/logo.svg"
                      alt=""
                    />
                  </Link>
                </div>

                <button
                  type="button"
                  className="inline-flex rounded-md p-2 text-black transition-all duration-200 hover:bg-gray-100 focus:bg-gray-100 lg:hidden"
                >
                  <svg
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M21.5 4.5H4.5V21.5H21.5V4.5Z"
                      fill="black"
                      stroke="black"
                      stroke-width="2"
                      stroke-linejoin="round"
                    />
                    <path
                      d="M19.5 2.5H2.5V19.5H19.5V2.5Z"
                      fill="#DD7DFF"
                      stroke="black"
                      stroke-width="2"
                      stroke-linejoin="round"
                    />
                    <path d="M6 15H16" stroke="black" stroke-width="2" />
                    <path d="M6 11H16" stroke="black" stroke-width="2" />
                    <path d="M6 7H16" stroke="black" stroke-width="2" />
                  </svg>
                </button>

                <div className="hidden border-b-2 border-pink-400 pl-4 pr-4 pb-2 lg:flex lg:items-center lg:justify-center lg:space-x-10">
                  <a
                    href="#"
                    title=""
                    className="text-base text-black transition-all duration-200 hover:text-opacity-80"
                  >
                    {" "}
                    Features{" "}
                  </a>

                  <a
                    href="#"
                    title=""
                    className="text-base text-black transition-all duration-200 hover:text-opacity-80"
                  >
                    {" "}
                    Solutions{" "}
                  </a>

                  <a
                    href="#"
                    title=""
                    className="text-base text-black transition-all duration-200 hover:text-opacity-80"
                  >
                    {" "}
                    Resources{" "}
                  </a>

                  <a
                    href="#"
                    title=""
                    className="text-base text-black transition-all duration-200 hover:text-opacity-80"
                  >
                    {" "}
                    Pricing{" "}
                  </a>
                </div>

                <div className="flex flex-row items-center">
                  <a
                    href="#"
                    title=""
                    className="mr-4 hidden items-center justify-center border-2 border-black bg-brutal-purple px-5 py-2.5 text-base font-semibold text-white shadow-brutalist-4 transition-all duration-200 hover:bg-red-400 hover:text-black hover:shadow-brutalist-16 focus:bg-brutal-red focus:text-black lg:inline-flex"
                    role="button"
                    onClick={() => {
                      signIn();
                    }}
                  >
                    {" "}
                    Log in{" "}
                  </a>

                  <a
                    href="#"
                    title=""
                    className="hidden items-center justify-center border-2 border-black bg-brutal-red px-5 py-2.5 text-base font-semibold text-white shadow-brutalist-4 transition-all duration-200 hover:bg-red-400 hover:text-black hover:shadow-brutalist-16 focus:bg-brutal-red focus:text-black lg:inline-flex"
                    role="button"
                    onClick={() => {
                      signIn("discord");
                    }}
                  >
                    {" "}
                    Sign up{" "}
                  </a>
                </div>
              </div>
            </div>
          </header>

          <section className=" bg-opacity-30 py-10 sm:py-16 lg:py-24">
            <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
              <div className="grid grid-cols-1 items-center gap-12 lg:grid-cols-2">
                <div>
                  <p className="text-base font-semibold uppercase tracking-wider text-blue-600">
                    powered by
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="100"
                      viewBox="0 0 338.667 83.339"
                      fill="#0f0f0f"
                    >
                      <path d="M200.154 32.427v.028c-.169 0-.339.028-.508.028s-.339-.028-.508-.028c-10.075 0-16.312 6.294-16.312 16.397v4.967c0 9.736 6.322 15.776 16.453 15.776a4.38 4.38 0 0 0 .621-.028c.141 0 .254.028.395.028 6.801 0 11.543-2.483 14.562-7.62l-6.011-3.472c-2.004 2.963-4.685 5.193-8.523 5.193-5.136 0-8.212-3.161-8.212-8.495V53.79h23.819v-5.87c0-9.426-6.18-15.494-15.776-15.494zm-.508 5.786c4.685.226 7.507 3.33 7.507 8.438v1.411h-15.07v-.819c0-5.644 2.681-8.805 7.563-9.031zm-36.998-5.758c-4.487 0-8.353 1.863-10.385 4.967l-.508.79v-4.911h-8.523v47.667h8.946v-16.65l.508.762c1.919 2.85 5.673 4.543 10.047 4.543h.226.197c7.366 0 14.788-4.798 14.788-15.55v-6.039c0-7.733-4.572-15.55-14.845-15.55l-.056-.028h-.197zm-2.088 6.717c5.193.085 8.41 3.612 8.41 9.257v5.192c0 5.644-3.246 9.144-8.495 9.257-4.882-.085-8.297-3.81-8.297-9.116v-5.334c0-5.362 3.443-9.144 8.382-9.257zm115.934-18.485l-17.215 48.09h9.68l3.302-10.301h18.795v.113l3.302 10.216h9.68l-17.243-48.09h-1.016l-.028-.028zm5.137 8.269l7.196 22.719h-14.45zm57.035-1.496v-6.773h-29.52v6.773h10.357v34.487h-10.357v6.773h29.52v-6.773h-10.357V27.46zm-97.139 4.996h-.254-.141c-4.995 0-8.551 1.693-10.301 4.939l-.536.988v-5.08h-8.523v35.446h8.946v-21.11c0-4.967 2.681-7.817 7.309-7.902 4.431.085 6.971 2.879 6.971 7.705v21.307h8.946V45.917c0-8.438-4.628-13.462-12.389-13.462zM114.473 19.699c-13.18 0-21.392 8.213-21.392 21.449v7.14c0 13.236 8.184 21.448 21.392 21.448h.198.197c13.18 0 21.392-8.212 21.392-21.448v-7.14c0-13.236-8.212-21.449-21.392-21.449h-.197zm.198 7.169c7.846.085 12.361 5.108 12.361 13.8v8.128c0 8.692-4.515 13.716-12.361 13.8-7.846-.085-12.362-5.108-12.362-13.8v-8.128c0-8.692 4.516-13.716 12.362-13.8zM36.751.001c-9.116 0-17.215 5.87-20.038 14.534A20.83 20.83 0 0 0 2.828 24.61C-1.744 32.512-.7 42.446 5.425 49.219 3.534 54.892 4.183 61.1 7.203 66.237c4.544 7.93 13.687 11.994 22.634 10.103a20.78 20.78 0 0 0 15.635 6.999c9.116 0 17.215-5.87 20.038-14.534 5.87-1.214 10.922-4.883 13.857-10.075 4.6-7.902 3.556-17.836-2.568-24.609v-.028a20.76 20.76 0 0 0-1.778-17.046C70.476 9.145 61.332 5.08 52.414 6.971A20.86 20.86 0 0 0 36.751.001zm0 5.419l-.028.028c3.669 0 7.197 1.27 10.019 3.613-.113.056-.339.197-.508.282L29.64 18.91c-.847.48-1.355 1.383-1.355 2.371v22.464l-7.14-4.12v-18.57A15.63 15.63 0 0 1 36.751 5.419zm19.99 6.54a15.62 15.62 0 0 1 13.566 7.825c1.806 3.161 2.483 6.858 1.862 10.442-.113-.085-.338-.197-.48-.282l-16.594-9.596a2.78 2.78 0 0 0-2.737 0L32.913 31.581V23.34l16.058-9.285a15.54 15.54 0 0 1 7.77-2.096zm-41.043 8.53v19.727c0 .988.508 1.863 1.355 2.371l19.416 11.204L29.3 57.94l-16.03-9.257a15.63 15.63 0 0 1-5.7-21.336 15.65 15.65 0 0 1 8.128-6.858zm37.196 4.882l16.058 9.257c7.479 4.318 10.018 13.857 5.7 21.336l.028.028c-1.834 3.161-4.713 5.588-8.128 6.83V43.095c0-.988-.508-1.891-1.355-2.37L45.753 29.492zm-11.797 6.802l8.185 4.741v9.454l-8.185 4.741-8.184-4.741v-9.454zm12.869 7.451l7.14 4.12v18.542c0 8.636-6.999 15.635-15.606 15.635v-.028c-3.641 0-7.197-1.27-9.991-3.612.113-.056.367-.198.508-.283l16.594-9.567c.847-.48 1.383-1.383 1.354-2.371zM49.309 51.76V60l-16.058 9.257c-7.479 4.29-17.018 1.75-21.336-5.701h.028c-1.834-3.133-2.484-6.858-1.863-10.442.113.085.339.197.48.282l16.594 9.596a2.78 2.78 0 0 0 2.737 0z" />
                    </svg>
                  </p>
                  <h1 className="mt-4 text-4xl font-bold text-black sm:text-6xl lg:mt-8 xl:text-8xl">
                    Use <span className="font-bold text-pink-400">AI</span> to
                    help you learn
                    <span className="font-bold text-purple-400">.</span>
                  </h1>
                  <p className="mt-4 text-base text-black sm:text-xl lg:mt-8">
                    Create a online curriculum tailored to your needs and
                    <br /> learn at your own pace.
                  </p>

                  <a
                    href="#"
                    title=""
                    className="mt-8 inline-flex items-center border-2 border-black bg-brutal-green px-6 py-4 font-semibold text-black shadow-brutalist-8 transition-all duration-200 hover:bg-green-400 hover:shadow-brutalist-16 focus:bg-brutal-green lg:mt-16"
                    role="button"
                  >
                    <span className="mr-2">start your journey</span>
                    <svg
                      width="32"
                      height="32"
                      viewBox="0 0 32 32"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path d="M6 6H28.6667V28.6667H6V6Z" fill="black" />
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M5.33337 5.99998C5.33337 5.63178 5.63184 5.33331 6.00004 5.33331H28.6667C29.0349 5.33331 29.3334 5.63178 29.3334 5.99998V28.6666C29.3334 29.0348 29.0349 29.3333 28.6667 29.3333H6.00004C5.63184 29.3333 5.33337 29.0348 5.33337 28.6666V5.99998ZM6.66671 6.66665V28H28V6.66665H6.66671Z"
                        fill="black"
                      />
                      <path
                        d="M3.33337 3.33331H26V26H3.33337V3.33331Z"
                        fill="#00FF75"
                      />
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M2.66663 3.33335C2.66663 2.96516 2.9651 2.66669 3.33329 2.66669H26C26.3682 2.66669 26.6666 2.96516 26.6666 3.33335V26C26.6666 26.3682 26.3682 26.6667 26 26.6667H3.33329C2.9651 26.6667 2.66663 26.3682 2.66663 26V3.33335ZM3.99996 4.00002V25.3334H25.3333V4.00002H3.99996Z"
                        fill="black"
                      />
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M18.781 14.6667L14.3905 10.2761L16.2761 8.3905L22.5523 14.6667L16.2761 20.9428L14.3905 19.0572L18.781 14.6667Z"
                        fill="black"
                      />
                      <path
                        fill-rule="evenodd"
                        clip-rule="evenodd"
                        d="M6.66663 16H20.6666V13.3333H6.66663V16Z"
                        fill="black"
                      />
                    </svg>
                  </a>

                  <p className="mt-5 text-gray-600">
                    Already joined us?{" "}
                    <a
                      href="#"
                      title=""
                      className="text-blue-500 underline transition-all duration-200 hover:underline"
                    >
                      Log in
                    </a>
                  </p>
                </div>

                <div>
                  <img className="w-full" src="/assets/hero.svg" alt="" />
                </div>
              </div>
            </div>
          </section>
        </div>
        <section className="bg-white pt-2 pb-16">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <div className="flex items-center justify-center">
                <div className="-mr-6 h-20 w-20 overflow-hidden rounded-full border-8 border-brutal-purple bg-gray-300 shadow-brutalist-8">
                  <Image
                    width={100}
                    height={100}
                    className="h-full w-full object-cover"
                    src="https://cdn.rareblocks.xyz/collection/celebration/images/cta/2/female-avatar-1.jpg"
                    alt=""
                  />
                </div>

                <div className="relative h-28 w-28 overflow-hidden rounded-full border-8 border-brutal-red bg-gray-300 shadow-brutalist-8">
                  <Image
                    width={100}
                    height={100}
                    className="h-full w-full object-cover"
                    src="https://cdn.rareblocks.xyz/collection/celebration/images/cta/2/male-avatar-1.jpg"
                    alt=""
                  />
                </div>

                <div className="-ml-6 h-20 w-20 overflow-hidden rounded-full border-8 border-brutal-yellow bg-gray-300 shadow-brutalist-8">
                  <Image
                    width={100}
                    height={100}
                    className="h-full w-full object-cover"
                    src="https://cdn.rareblocks.xyz/collection/celebration/images/cta/2/female-avatar-2.jpg"
                    alt=""
                  />
                </div>
              </div>

              <h2 className="mt-8 text-3xl font-bold leading-tight text-black sm:text-4xl lg:mt-12 lg:text-5xl">
                Join <span className="border-b-8 border-yellow-300">5,482</span>{" "}
                other learners 📚
              </h2>
              <p className="mx-auto mt-6 max-w-xl text-xl text-gray-600 md:mt-10">
                Amet minim mollit non deserunt ullamco est sit aliqua dolor do
                amet sint. Velit officia consequat duis.
              </p>

              <a
                href="#"
                title=""
                className="mt-6 hidden items-center justify-center border-2 border-black bg-brutal-purple px-5 py-2.5 text-base font-semibold text-white shadow-brutalist-4 transition-all duration-200 hover:bg-red-400 hover:text-black hover:shadow-brutalist-16 focus:bg-brutal-red focus:text-black lg:inline-flex"
                role="button"
                onClick={() => {
                  signIn();
                }}
              >
                {" "}
                Join Now{" "}
              </a>
            </div>
          </div>
        </section>

        <section className="bg-white py-10 sm:py-16 lg:py-24">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-4xl text-center">
              <h1 className="text-4xl font-bold text-black sm:text-6xl lg:text-7xl">
                what people are saying about{" "}
                <div className="relative inline-flex">
                  <span className="absolute inset-x-0 bottom-0 border-b-[30px] border-[#4ADE80]"></span>
                  <h1 className="relative text-4xl font-bold text-black sm:text-6xl lg:text-7xl">
                    teachyourself
                  </h1>
                </div>
              </h1>
            </div>

            <div className="mx-auto mt-8 grid max-w-xl grid-cols-1 gap-x-6 gap-y-6 text-center sm:mt-12 lg:mt-20 lg:max-w-full lg:grid-cols-3 xl:gap-x-12">
              <div className="overflow-hidden rounded-md border-2 border-black bg-brutal-blue shadow-brutalist-8">
                <div className="px-8 py-12">
                  <div className="relative mx-auto h-24 w-24">
                    <img
                      className="relative mx-auto h-24 w-24 rounded-full object-cover"
                      src="https://cdn.rareblocks.xyz/collection/celebration/images/testimonials/1/avatar-1.jpg"
                      alt=""
                    />
                    <div className="absolute top-0 right-0 flex h-7 w-7 items-center justify-center rounded-full bg-blue-600">
                      <svg
                        className="h-4 w-4 text-white"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                      >
                        <path d="M20.309 17.708C22.196 15.66 22.006 13.03 22 13V5a1 1 0 0 0-1-1h-6c-1.103 0-2 .897-2 2v7a1 1 0 0 0 1 1h3.078a2.89 2.89 0 0 1-.429 1.396c-.508.801-1.465 1.348-2.846 1.624l-.803.16V20h1c2.783 0 4.906-.771 6.309-2.292zm-11.007 0C11.19 15.66 10.999 13.03 10.993 13V5a1 1 0 0 0-1-1h-6c-1.103 0-2 .897-2 2v7a1 1 0 0 0 1 1h3.078a2.89 2.89 0 0 1-.429 1.396c-.508.801-1.465 1.348-2.846 1.624l-.803.16V20h1c2.783 0 4.906-.771 6.309-2.292z"></path>
                      </svg>
                    </div>
                  </div>

                  <blockquote className="text-xl font-semibold italic text-black">
                    <svg
                      aria-hidden="true"
                      className="h-10 w-10 text-white"
                      viewBox="0 0 24 27"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M14.017 18L14.017 10.609C14.017 4.905 17.748 1.039 23 0L23.995 2.151C21.563 3.068 20 5.789 20 8H24V18H14.017ZM0 18V10.609C0 4.905 3.748 1.038 9 0L9.996 2.151C7.563 3.068 6 5.789 6 8H9.983L9.983 18L0 18Z"
                        fill="currentColor"
                      />
                    </svg>
                    <p>
                      Amet minim mollit non deserunt ullam co est sit aliqua
                      dolor do amet sint. Velit officia consequat duis enim
                      velit mollit. Exercitation veniam consequat
                    </p>
                    <div className="flex w-full flex-row justify-end">
                      <svg
                        aria-hidden="true"
                        className="h-10 w-10 rotate-180 text-white"
                        viewBox="0 0 24 27"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M14.017 18L14.017 10.609C14.017 4.905 17.748 1.039 23 0L23.995 2.151C21.563 3.068 20 5.789 20 8H24V18H14.017ZM0 18V10.609C0 4.905 3.748 1.038 9 0L9.996 2.151C7.563 3.068 6 5.789 6 8H9.983L9.983 18L0 18Z"
                          fill="currentColor"
                        />
                      </svg>
                    </div>
                  </blockquote>
                  <p className="tex-tblack mt-9 text-base font-semibold">
                    Jenny Wilson
                  </p>
                  <p className="mt-1 text-base text-white">
                    Project Manager at Microsoft
                  </p>
                </div>
              </div>

              <div className="overflow-hidden rounded-md border-2 border-black  bg-brutal-red shadow-brutalist-8">
                <div className="px-8 py-12">
                  <div className="relative mx-auto h-24 w-24">
                    <img
                      className="relative mx-auto h-24 w-24 rounded-full object-cover"
                      src="https://cdn.rareblocks.xyz/collection/celebration/images/testimonials/1/avatar-2.jpg"
                      alt=""
                    />
                    <div className="absolute top-0 right-0 flex h-7 w-7 items-center justify-center rounded-full bg-blue-600">
                      <svg
                        className="h-4 w-4 text-white"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                      >
                        <path d="M20.309 17.708C22.196 15.66 22.006 13.03 22 13V5a1 1 0 0 0-1-1h-6c-1.103 0-2 .897-2 2v7a1 1 0 0 0 1 1h3.078a2.89 2.89 0 0 1-.429 1.396c-.508.801-1.465 1.348-2.846 1.624l-.803.16V20h1c2.783 0 4.906-.771 6.309-2.292zm-11.007 0C11.19 15.66 10.999 13.03 10.993 13V5a1 1 0 0 0-1-1h-6c-1.103 0-2 .897-2 2v7a1 1 0 0 0 1 1h3.078a2.89 2.89 0 0 1-.429 1.396c-.508.801-1.465 1.348-2.846 1.624l-.803.16V20h1c2.783 0 4.906-.771 6.309-2.292z"></path>
                      </svg>
                    </div>
                  </div>

                  <blockquote className="text-xl font-semibold italic text-black">
                    <svg
                      aria-hidden="true"
                      className="h-10 w-10 text-white"
                      viewBox="0 0 24 27"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M14.017 18L14.017 10.609C14.017 4.905 17.748 1.039 23 0L23.995 2.151C21.563 3.068 20 5.789 20 8H24V18H14.017ZM0 18V10.609C0 4.905 3.748 1.038 9 0L9.996 2.151C7.563 3.068 6 5.789 6 8H9.983L9.983 18L0 18Z"
                        fill="currentColor"
                      />
                    </svg>
                    <p>
                      Amet minim mollit non deserunt ullam co est sit aliqua
                      dolor do amet sint. Velit officia consequat duis enim
                      velit mollit. Exercitation veniam consequat
                    </p>
                    <div className="flex w-full flex-row justify-end">
                      <svg
                        aria-hidden="true"
                        className="h-10 w-10 rotate-180 text-white"
                        viewBox="0 0 24 27"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M14.017 18L14.017 10.609C14.017 4.905 17.748 1.039 23 0L23.995 2.151C21.563 3.068 20 5.789 20 8H24V18H14.017ZM0 18V10.609C0 4.905 3.748 1.038 9 0L9.996 2.151C7.563 3.068 6 5.789 6 8H9.983L9.983 18L0 18Z"
                          fill="currentColor"
                        />
                      </svg>
                    </div>
                  </blockquote>
                  <p className="tex-tblack mt-9 text-base font-semibold">
                    Robert Fox
                  </p>
                  <p className="mt-1 text-base text-white">
                    Founder at Brain.co
                  </p>
                </div>
              </div>

              <div className="overflow-hidden rounded-md border-2 border-black bg-brutal-purple shadow-brutalist-8">
                <div className="px-8 py-12">
                  <div className="relative mx-auto h-24 w-24">
                    <img
                      className="relative mx-auto h-24 w-24 rounded-full object-cover"
                      src="https://cdn.rareblocks.xyz/collection/celebration/images/testimonials/1/avatar-3.jpg"
                      alt=""
                    />
                    <div className="absolute top-0 right-0 flex h-7 w-7 items-center justify-center rounded-full bg-blue-600">
                      <svg
                        className="h-4 w-4 text-white"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        fill="currentColor"
                      >
                        <path d="M20.309 17.708C22.196 15.66 22.006 13.03 22 13V5a1 1 0 0 0-1-1h-6c-1.103 0-2 .897-2 2v7a1 1 0 0 0 1 1h3.078a2.89 2.89 0 0 1-.429 1.396c-.508.801-1.465 1.348-2.846 1.624l-.803.16V20h1c2.783 0 4.906-.771 6.309-2.292zm-11.007 0C11.19 15.66 10.999 13.03 10.993 13V5a1 1 0 0 0-1-1h-6c-1.103 0-2 .897-2 2v7a1 1 0 0 0 1 1h3.078a2.89 2.89 0 0 1-.429 1.396c-.508.801-1.465 1.348-2.846 1.624l-.803.16V20h1c2.783 0 4.906-.771 6.309-2.292z"></path>
                      </svg>
                    </div>
                  </div>

                  <blockquote className="text-xl font-semibold italic text-black">
                    <svg
                      aria-hidden="true"
                      className="h-10 w-10 text-white"
                      viewBox="0 0 24 27"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M14.017 18L14.017 10.609C14.017 4.905 17.748 1.039 23 0L23.995 2.151C21.563 3.068 20 5.789 20 8H24V18H14.017ZM0 18V10.609C0 4.905 3.748 1.038 9 0L9.996 2.151C7.563 3.068 6 5.789 6 8H9.983L9.983 18L0 18Z"
                        fill="currentColor"
                      />
                    </svg>
                    <p>
                      Amet minim mollit non deserunt ullam co est sit aliqua
                      dolor do amet sint. Velit officia consequat duis enim
                      velit mollit. Exercitation veniam consequat
                    </p>
                    <div className="flex w-full flex-row justify-end">
                      <svg
                        aria-hidden="true"
                        className="h-10 w-10 rotate-180 text-white"
                        viewBox="0 0 24 27"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M14.017 18L14.017 10.609C14.017 4.905 17.748 1.039 23 0L23.995 2.151C21.563 3.068 20 5.789 20 8H24V18H14.017ZM0 18V10.609C0 4.905 3.748 1.038 9 0L9.996 2.151C7.563 3.068 6 5.789 6 8H9.983L9.983 18L0 18Z"
                          fill="currentColor"
                        />
                      </svg>
                    </div>
                  </blockquote>

                  <p className="tex-tblack mt-9 text-base font-semibold">
                    Kristin Watson
                  </p>
                  <p className="mt-1 text-base text-white">
                    UX Designer at Google
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="pt-6 pb-6 md:pt-10 md:pb-10 lg:pt-16 lg:pb-16">
          <div className="bg-white">
            <div className="mx-auto max-w-7xl px-6 lg:px-8">
              <div className="sm:text-center">
                <h1 className="text-4xl font-bold text-black sm:text-6xl lg:text-7xl">
                  <div className="relative inline-flex">
                    <span className="absolute inset-x-0 bottom-0 border-b-[30px] border-[#4ADE80]"></span>
                    <h1 className="relative text-4xl font-bold text-black sm:text-6xl lg:text-7xl">
                      AI Generated Curriculum
                    </h1>
                  </div>
                </h1>
                <p className="mt-6 text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
                  A better way to learn
                </p>
                <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-gray-600">
                  Lorem ipsum dolor sit amet consect adipisicing elit. Possimus
                  magnam voluptatum cupiditate veritatis in accusamus quisquam.
                </p>
              </div>

              <div className="mt-20 max-w-lg sm:mx-auto md:max-w-none">
                <div className="grid grid-cols-1 gap-y-16 md:grid-cols-2 md:gap-x-12 md:gap-y-16">
                  <div className="relative flex flex-col gap-6 sm:flex-row md:flex-col lg:flex-row">
                    <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-500 text-white sm:shrink-0">
                      <svg
                        className="h-8 w-8"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        aria-hidden="true"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0121 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0112 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 013 12c0-1.605.42-3.113 1.157-4.418"
                        />
                      </svg>
                    </div>
                    <div className="sm:min-w-0 sm:flex-1">
                      <p className="text-lg font-semibold leading-8 text-gray-900">
                        Competitive exchange rates
                      </p>
                      <p className="mt-2 text-base leading-7 text-gray-600">
                        Lorem ipsum, dolor sit amet consectetur adipisicing
                        elit. Maiores impedit perferendis suscipit eaque, iste
                        dolor cupiditate blanditiis ratione.
                      </p>
                    </div>
                  </div>

                  <div className="relative flex flex-col gap-6 sm:flex-row md:flex-col lg:flex-row">
                    <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-500 text-white sm:shrink-0">
                      <svg
                        className="h-8 w-8"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        aria-hidden="true"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M12 3v17.25m0 0c-1.472 0-2.882.265-4.185.75M12 20.25c1.472 0 2.882.265 4.185.75M18.75 4.97A48.416 48.416 0 0012 4.5c-2.291 0-4.545.16-6.75.47m13.5 0c1.01.143 2.01.317 3 .52m-3-.52l2.62 10.726c.122.499-.106 1.028-.589 1.202a5.988 5.988 0 01-2.031.352 5.988 5.988 0 01-2.031-.352c-.483-.174-.711-.703-.59-1.202L18.75 4.971zm-16.5.52c.99-.203 1.99-.377 3-.52m0 0l2.62 10.726c.122.499-.106 1.028-.589 1.202a5.989 5.989 0 01-2.031.352 5.989 5.989 0 01-2.031-.352c-.483-.174-.711-.703-.59-1.202L5.25 4.971z"
                        />
                      </svg>
                    </div>
                    <div className="sm:min-w-0 sm:flex-1">
                      <p className="text-lg font-semibold leading-8 text-gray-900">
                        No hidden fees
                      </p>
                      <p className="mt-2 text-base leading-7 text-gray-600">
                        Lorem ipsum, dolor sit amet consectetur adipisicing
                        elit. Maiores impedit perferendis suscipit eaque, iste
                        dolor cupiditate blanditiis ratione.
                      </p>
                    </div>
                  </div>

                  <div className="relative flex flex-col gap-6 sm:flex-row md:flex-col lg:flex-row">
                    <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-500 text-white sm:shrink-0">
                      <svg
                        className="h-8 w-8"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        aria-hidden="true"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z"
                        />
                      </svg>
                    </div>
                    <div className="sm:min-w-0 sm:flex-1">
                      <p className="text-lg font-semibold leading-8 text-gray-900">
                        Transfers are instant
                      </p>
                      <p className="mt-2 text-base leading-7 text-gray-600">
                        Lorem ipsum, dolor sit amet consectetur adipisicing
                        elit. Maiores impedit perferendis suscipit eaque, iste
                        dolor cupiditate blanditiis ratione.
                      </p>
                    </div>
                  </div>

                  <div className="relative flex flex-col gap-6 sm:flex-row md:flex-col lg:flex-row">
                    <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-indigo-500 text-white sm:shrink-0">
                      <svg
                        className="h-8 w-8"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke-width="1.5"
                        stroke="currentColor"
                        aria-hidden="true"
                      >
                        <path
                          stroke-linecap="round"
                          stroke-linejoin="round"
                          d="M10.5 1.5H8.25A2.25 2.25 0 006 3.75v16.5a2.25 2.25 0 002.25 2.25h7.5A2.25 2.25 0 0018 20.25V3.75a2.25 2.25 0 00-2.25-2.25H13.5m-3 0V3h3V1.5m-3 0h3m-3 18.75h3"
                        />
                      </svg>
                    </div>
                    <div className="sm:min-w-0 sm:flex-1">
                      <p className="text-lg font-semibold leading-8 text-gray-900">
                        Mobile notifications
                      </p>
                      <p className="mt-2 text-base leading-7 text-gray-600">
                        Lorem ipsum, dolor sit amet consectetur adipisicing
                        elit. Maiores impedit perferendis suscipit eaque, iste
                        dolor cupiditate blanditiis ratione.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
